### ISSUE TITLE
need a help on escaping the paranthesis 

### ISSUE THREAD

**Issue by Rashmi-Nuviso** [google/textfsm#10]
Hi All ,

can anybody help me how do  i escape the paranthesis 

my requirement is to pull the X86_64_LINUX_IOSD-UNIVERSALK9-M

from the build from the  cisco show version  output 

Cisco IOS Software, CSR1000V Software (X86_64_LINUX_IOSD-UNIVERSALK9-M),

since textfsm has the definition where most of the pattern we want to fetch it needs to be grouped 

if i try like 

pattern = \((.*)\) to extract the (X86_64_LINUX_IOSD-UNIVERSALK9-M)

the textFSM throws the error .

any help on this will be appreciated .

**Comment by buxtronix** [comment]
You can do this by escaping the parens:

```
Value Build (\S+)

Start
  ^Cisco IOS Software.*\(${Build}\)

```
