### ISSUE TITLE
show cdp neighbor detail template fails when output includes VTP VTP Management Domain Name: null

### ISSUE THREAD

**Issue by siddharth-chhabra** [google/textfsm#100]
The template for nxos show cdp neighbor DETAIL fails with an output like this that includes VTP Domain Name 

Device ID:Switch
      VTP Management Domain Name: null
  
      Interface address(es):
      Platform: cisco WS-C3850-48P, Capabilities: Switch IGMP Filtering
      Interface: mgmt0, Port ID (outgoing port): GigabitEthernet1/0/2
      Holdtime: 127 sec

**Comment by siddharth-chhabra** [comment]
stdout_lines:
    - - '----------------------------------------'
      - Device ID:Switch
      - 'VTP Management Domain Name: null'
      - ''
      - 'Interface address(es):'
      - 'Platform: cisco WS-C3850-48P, Capabilities: Switch IGMP Filtering '
      - 'Interface: mgmt0, Port ID (outgoing port): GigabitEthernet1/0/2'
      - 'Holdtime: 127 sec'
      - ''
      - 'Version:'
      - Cisco IOS Software, Catalyst L3 Switch Software (CAT3K_CAA-UNIVERSALK9-M), Version 15.2(2)E6, RELEASE SOFTWARE (fc1)
      - 'Technical Support: http://www.cisco.com/techsupport'
      - Copyright (c) 1986-2016 by Cisco Systems, Inc.
      - Compiled Sat 17-Dec-16 00:22 by prod_rel_team
      - ''
      - 'Advertisement Version: 2'
      - ''
      - 'Native VLAN: 316'
      - 'Duplex: full'

**Comment by xdai555** [comment]
> The template for nxos show cdp neighbor DETAIL fails with an output like this that includes VTP Domain Name
> 
> Device ID:Switch VTP Management Domain Name: null
> 
> ```
>   Interface address(es):
>   Platform: cisco WS-C3850-48P, Capabilities: Switch IGMP Filtering
>   Interface: mgmt0, Port ID (outgoing port): GigabitEthernet1/0/2
>   Holdtime: 127 sec
> ```

Hi, it looks like you should submit an issue on [ntc-templates](https://github.com/networktocode/ntc-templates/issues).

**Comment by harro** [comment]
Sorry, show cdp ... is not one of our example templates. I think @xdai555 has given the answer you need.
