### ISSUE TITLE
Only the last set of data can be matched

### ISSUE THREAD

**Issue by Darren-qu** [google/textfsm#102]
1. template matching rules
![image](https://user-images.githubusercontent.com/86956804/170949481-e8fb1612-f8e0-47af-b9e4-ffc3a91af00e.png)

2. data to be processed
![image](https://user-images.githubusercontent.com/86956804/170949117-29053072-6b5a-4cd5-8fde-22196fe20aa4.png)

3. operation result
![image](https://user-images.githubusercontent.com/86956804/170949452-a6cf0eaa-ef49-44a7-8f8e-b76a7b76fa89.png)

encountered a problem: Only the last piece of data can be matched, the interface data in the middle cannot be matched, can you help me?

**Comment by geekstrident** [comment]
Can you try the below template?

```
Value Required SnoopingStateV4 (\w+)
Value Required SnoopingInterface01 (\S+)
Value Required SnoopingTrusted01 (\w+)
Value Required SnoopingInterface02 (\S+)
Value Required SnoopingTrusted02 (\w+)

Start
  ^\s+DHCPv4\s+snopping\s+:\s+${SnoopingStateV4} -> Continue
  ^\s+DHCP\s+snopping\s+running\s+information\s+for\s+interface\s+${SnoopingInterface01}\s+: -> Continue
  ^\s+Trusted interface\s+:\s+${SnoopingTrusted01} -> Continue
  ^\s+DHCP\s+snopping\s+running\s+information\s+for\s+interface\s+${SnoopingInterface02}\s+: -> Continue
  ^\s+Trusted\s+interface\s+:\s+${SnoopingTrusted02} -> Record
```

**Comment by harro** [comment]
Closing on the assumption this suggested template has resolved the issue. Reopen if that is not the case?
