### ISSUE TITLE
Can't install textfsm 1.1.3

### ISSUE THREAD

**Issue by clj** [google/textfsm#105]
Hi, I can't install very recently released textfsm 1.1.3. This seems to be because:

* No wheel has been uploaded for 1.1.3 (https://pypi.org/project/textfsm/1.1.3/#files vs https://pypi.org/project/textfsm/1.1.2/#files)
* setup.py does not specify `six` as a setup_requires dependency, so pip fails to install from source:

```
pip install textfsm
Collecting textfsm
  Downloading textfsm-1.1.3.tar.gz (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.5/55.5 KB 1.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/km/bpjt_xps0174w9mlsh18tjbm0000gn/T/pip-install-t1l_cd8g/textfsm_b7c4791da8d447b98c4e9ddb9eb14469/setup.py", line 20, in <module>
          import textfsm
        File "/private/var/folders/km/bpjt_xps0174w9mlsh18tjbm0000gn/T/pip-install-t1l_cd8g/textfsm_b7c4791da8d447b98c4e9ddb9eb14469/textfsm/__init__.py", line 11, in <module>
          from textfsm.parser import *
        File "/private/var/folders/km/bpjt_xps0174w9mlsh18tjbm0000gn/T/pip-install-t1l_cd8g/textfsm_b7c4791da8d447b98c4e9ddb9eb14469/textfsm/parser.py", line 41, in <module>
          import six
      ModuleNotFoundError: No module named 'six'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by clj** [comment]
Actually, pip doesn't seem to do setup_requires, but it seems possible to get around all this by setting the version in setup.cfg, e.g.: #106

**Comment by ColonelBundy** [comment]
Same issue here...

**Comment by shustinm** [comment]
Same issue for me.
This is because the release of [textfsm 1.1.3](https://pypi.org/project/textfsm/1.1.3/#files) doesn't include a built wheel distribution like on [textfsm 1.1.2](https://pypi.org/project/textfsm/1.1.2/#files). Specifying 1.1.2 in the requirement set should work.

**Comment by jobec** [comment]
Same issue here.
@jefvantongerloo This changed:  https://github.com/google/textfsm/compare/v1.1.2...v1.1.3

**Comment by edo248** [comment]
Just spent some time debugging this to find out that install fails because there's not wheel in the latest version (as @shustinm  mentioned).

Just to add to this build without wheel fails because `setup py` imports own package before even starting the install https://github.com/google/textfsm/blob/master/setup.py#L20 
then there's a ` import *` in https://github.com/google/textfsm/blob/master/textfsm/__init__.py#L11 that calls parser which reaches for six. All of this happening before setup even started.

**Comment by MrPaulAR** [comment]
As a workaround you can install six prior to textfsm 1.1.3.  It's a bit hacky but works until a fix is released.

**Comment by harro** [comment]
Missed uploading the wheel, added it now. And 'pip install textfsm' installs latest release on a clean environment.
