### ISSUE TITLE
How to assign a default value

### ISSUE THREAD

**Issue by BatD2** [google/textfsm#111]
Is there a way to assign a default string to Value field, if the input for this field is blank. 
Use case is a setting which only appear in CLI when there in error, but not there if everything work ok. 
So I have a Value called "STATUS" and I want to assign "ok" to it, if the status is blank.

**Comment by harro** [comment]
Easiest way to do that would be in post-processing of the table. Once you've matched the data and returned the python table, then walk the table and replace the missing data in the column with the desired value.

Or in other words, 'blank' is a value in this context, and substituting "ok" would be a cosmetic change probably best done outside of textfsm.
