### ISSUE TITLE
No need to have future as dependency

### ISSUE THREAD

**Issue by frenzymadness** [google/textfsm#115]
`future` is listed in dependencies but I cannot find a usage of it in the project and therefore I think it can be removed from the list. `future` is broken with Python 3.12 and will be even more with 3.13.

https://github.com/google/textfsm/blob/a4c2f824eb53d32ccae810068867a58cb9be17fe/setup.py#L56

**Comment by harro** [comment]
You are probably right. Away on holidays at the moment l, will take a look
when backm

**Comment by frenzymadness** [comment]
I see, thank you.

**Comment by harro** [comment]
Opened issue #119 to clean the legacy code

**Comment by harro** [comment]
#121 This change is in now
