### ISSUE TITLE
Tarball on github reported as 1.1.3 is 1.1.2

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [google/textfsm#118]
Downloading the tarball from github and unpacking shows:

```
conjecture:/tmp/tmp.s4TjkmFTgr% wget -q https://github.com/google/textfsm/archive/v1.1.3.tar.gz
conjecture:/tmp/tmp.s4TjkmFTgr% tar zxf v1.1.3.tar.gz 
conjecture:/tmp/tmp.s4TjkmFTgr% tail -n 3 textfsm-1.1.3/textfsm/__init__.py
from textfsm.parser import *

__version__ = '1.1.2'
```
Looks like the `__init__.py` change wasn't tagged for 1.1.3.

**Comment by harro** [comment]
Yeah, its v1.1.3 in all ways otherwise.

I'm going to close this one as a no-op. We'll release a v2.0.0 shortly and this should resolve the issue.
