### ISSUE TITLE
Remove v2 to v3 migration libraries

### ISSUE THREAD

**Issue by harro** [google/textfsm#119]
Remove dependencies on 'six' and 'future'
Probably time we made a clean v3.0 version

**Comment by a-detiste** [comment]
Hi, you want a PR ?

https://wiki.debian.org/Python3-six-removal#preview
https://salsa.debian.org/detiste-guest/python3-six-removal

**Comment by harro** [comment]
#121

**Comment by harro** [comment]
Thanks for the offer @a-detiste. I found some spare time this week, so was able to put together the changes.

**Comment by a-detiste** [comment]
That's one biiiiig commit 😁
