### ISSUE TITLE
'show memory statistics' cisco switch/rotuer template textfsm

### ISSUE THREAD

**Issue by NedySuprianto** [google/textfsm#15]
Template Creation Help
would like have template 'show memory statistic' cisco switch/router :)

**Comment by bewing** [comment]
Have you looked at https://github.com/networktocode/ntc-templates ? A large number of TextFSM templates are maintained there.

**Comment by NedySuprianto** [comment]
i already looked at there,but they dont have 'show memory statistic' TextFSM template

**Comment by harro** [comment]
The code lab - https://github.com/google/textfsm/wiki/Code-Lab
should get you started writing new templates. You need to decide what the relevant data is that you intend to pull from the output and that will drive the template design.

I imagine ntc-templates would be open to new submissions, and you may be able to ask for help from the contributors there.
