### ISSUE TITLE
Loading fcntl in terminal breaks windows load on Netmiko

### ISSUE THREAD

**Issue by ktbyers** [google/textfsm#20]
I wanted to added textfsm parsing into the output of network device show commands in the Netmiko library, but the terminal.py module imports fcntl (which breaks Windows support):

https://github.com/google/textfsm/blob/master/terminal.py#L28

For use in TerminalSize() function. My use case doesn't use this TerminalSize() function.

Would you be willing to make that import conditional? 

For example, something like the following:

```
try:
    import fcntl
    USE_FCNTL = True
except ImportError:
    USE_FCNTL = False
``` 

Then on TerminalSize() something like:

```
def TerminalSize():
  """Returns terminal length and width as a tuple."""
  try:
    with open(os.ctermid(), 'r') as tty_instance:
      if USE_FCNTL:
          length_width = struct.unpack(
              'hh', fcntl.ioctl(tty_instance.fileno(), termios.TIOCGWINSZ, '1234'))
      else:
          # Basically raise an error so it falls to your other try/except handler
          raise OSError()
  except (IOError, OSError):
    try:
      length_width = (int(os.environ['LINES']),
                      int(os.environ['COLUMNS']))
    except (ValueError, KeyError):
      length_width = (24, 80)
  return length_width
```

If you are willing to accept a PR similar to this, I will write it and submit it.

**Comment by ktbyers** [comment]
This solution won't work. Will come up with a different solution.

**Comment by harro** [comment]
Any update on this?

**Comment by ktbyers** [comment]
I will close...I re-wrote part of textfsm and included it in Netmiko basically the things that were causing windows to break were not relevant to my use case.
