### ISSUE TITLE
Documentation about 'forward match' style

### ISSUE THREAD

**Issue by lboue** [google/textfsm#22]
Hello,

I have read the WIKI page and I noticed in the [Using 'List'](https://github.com/google/textfsm/wiki/Code-Lab#using-list) section this section:

> This example was somewhat more complex than the average List usage. If there is a clear delimiter between rows, then that can be used for the Record rather than having to do the 'forward match' style here.

Can you explain that 'forward match' style in this WIKI documentation, please?

Regards,
Ludovic

**Comment by 1001QAdotNET** [comment]
You have the explanation right there.
Basically he is showing you how to check any number of lines between two lines of the same type.
I think that forward match is exactly that...keep processing lines till you get the next similar line and then record the data

Your rules are like this

interface Loopback1
interface Ethe1/1
  speed 100
  duplex full

Value Required Interface (\S+)
Value Speed (\d+)
Value Duplex (full)

Start
 ^interface ->Continue. Record        #this will not save the record at the first hit because $Interface=''
 ^\s+speed ${Speed}
 ^\s+duplex ${Duplex}
 ^\interface ${Interface}

so you are saving the record only after looking forward for each interface line, processing the config lines and save when you hit the next "interface line" 

This is an important trick because that is the only way to look ahead... as far as I can tell (might be wrong I am just started using this)

**Comment by lboue** [comment]
Hello,

My case seems more tricky than yours because I need to parse a VLAN list and each line have a port list: 
```
VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Gi0/1
10   Management                       active    
50   VLan50                           active    Fa0/1, Fa0/2, Fa0/3, Fa0/4, Fa0/5, Fa0/6, Fa0/7, Fa0/8, Fa0/9
                                                Fa0/10, Fa0/11, Fa0/12
60   VLan60                           active    Fa0/13, Fa0/14, Fa0/15, Fa0/16, Fa0/17, Fa0/18, Fa0/19, Fa0/20
Fa0/21, Fa0/22, Fa0/23, Fa0/24
```
Regards,
Ludovic

**Comment by harro** [comment]
For multiple entries that wrap onto new lines then there are a couple of approaches depending on how much post processing you want to do with the data.

Here is and example template for the command 'show mac-address-table' on a Cisco device - it collecting Ports for each MAC address:

```
Value Key MacAddress (\S+)
Value Required Vlan (\S+)
Value Required Type (\w+)
Value Learn (Yes|No)
Value Age (\d+|-)
Value List Ports (\S+)

Start
  ^(-------\+|---------\+) -> MacTable_1
  ^(------\+|----\+) -> MacTable_2
  ^(----\s) -> MacTable_3

MacTable_1
  ^(\s*\S+\s+\S+|$$) -> Continue.Record
  ^\s*${Vlan}\s+${MacAddress}\s+${Type}\s+\S+\s+${Ports}
  ^\s+${Ports}
  ^Multicast Entries -> End

MacTable_2
  ^(\*|\s)\S*\s+\d+ -> Continue.Record
  ^(\*|\s)\S*\s+${Vlan}\s+${MacAddress}\s+${Type}\s+${Learn}\s+${Age}\s+${Ports}
  ^\s+${Ports}

MacTable_3
  ^\s*\S+\s+\S+\s+\w+\s+\S+ -> Continue.Record
  ^\s*${Vlan}\s+${MacAddress}\s+${Type}\s+${Ports}
  ^\s+${Ports}
```

In this case each entry in the Ports list would need to be further split into the individual ports.

If you don't fancy doing any post processing, then this template walks through the output of 'show vlan' matching a port one at a time for the same line of input.

In my mind this is a little more of an exotic and approach.

```
Value Vlan (\d+)
Value Name (\S+)
Value Status (\S+)
Value List Ports ([^\s,]+)

Start
  ^----- -> Vlan

Vlan
  ^\d -> Continue.Record
  ^\d+\s+\S+\s+\S+\s+${Ports} -> Continue
  ^\d+\s+\S+\s+\S+\s+\S+, ${Ports} -> Continue
  ^\d+\s+\S+\s+\S+\s+\S+, \S+, ${Ports} -> Continue
  ^\d+\s+\S+\s+\S+\s+\S+, \S+, \S+, ${Ports} -> Continue
  ^\d+\s+\S+\s+\S+\s+\S+, \S+, \S+, \S+, ${Ports} -> Continue
  ^\d+\s+\S+\s+\S+\s+\S+, \S+, \S+, \S+, \S+, ${Ports} -> Continue
  ^\d+\s+\S+\s+\S+\s+\S+, \S+, \S+, \S+, \S+, \S+, ${Ports} -> Continue
  ^\d+\s+\S+\s+\S+\s+\S+, \S+, \S+, \S+, \S+, \S+, \S+, ${Ports} -> Continue
  ^${Vlan}\s+${Name}\s+${Status} -> Next
  ^\s+\S+, \S+, \S+, \S+, \S+, \S+, ${Ports} -> Continue
  ^\s+\S+, \S+, \S+, \S+, \S+, ${Ports} -> Continue
  ^\s+\S+, \S+, \S+, \S+, ${Ports} -> Continue
  ^\s+\S+, \S+, \S+, ${Ports} -> Continue
  ^\s+\S+, \S+, ${Ports} -> Continue
  ^\s+\S+, ${Ports} -> Continue
  ^\s+${Ports} -> Next
```
