### ISSUE TITLE
Include COPYING file in pypi package

### ISSUE THREAD

**Issue by javierpena** [google/textfsm#26]
I am packaging textfsm for Fedora. One of the Fedora requirements is that the license file (COPYING in this case) is included as part of the source tarball [1]. Looking at the PyPi package, this file is not included, although it is present in the Git repository.

Thanks!

[1]- https://fedoraproject.org/wiki/Packaging:LicensingGuidelines#License_Text

**Comment by harro** [comment]
Uploaded a new pypi package with the file included.
   pip install textfsm==0.4.0
