### ISSUE TITLE
Cannot clone repository

### ISSUE THREAD

**Issue by bewing** [google/textfsm#4]
When attempting to clone this repo, I get the following error:

```
git clone git@github.com:google/textfsm.git
Cloning into 'textfsm'...
Warning: Permanently added the RSA host key for IP address '192.30.252.131' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by verbosemode** [comment]
This command won't work unless you have [SSH key](https://help.github.com/articles/which-remote-url-should-i-use/#cloning-with-ssh) authentication configured.

Try the HTTPS url:

git clone https://github.com/google/textfsm.git

**Comment by bewing** [comment]
Weird, HTTPS was failing yesterday (taking forever, timing out), and I assumed that the SSH failure was more verbose.  Both methods of cloning work today, though.
