### ISSUE TITLE
Cannot install due to textfsm issue

### ISSUE THREAD

**Issue by egondragon** [google/textfsm#41]
Hi All
I have a critical issue with textfsm and gtextfsm:
When I try an installation of a module called pycsco, I encountered this error message:
: =============================
sudo -H pip install pycsco --proxy="http://proxy.rd.francetelecom.fr:8080"
Collecting pycsco
  Downloading https://files.pythonhosted.org/packages/55/6d/47e3fc0ae13d34a87f6328cb724f65e0484ce76b21de23e5767ecdfeddef/pycsco-0.3.5.tar.gz (54kB)
    100% |████████████████████████████████| 61kB 1.7MB/s
Collecting gtextfsm==0.2.1 (from pycsco)
  Downloading https://files.pythonhosted.org/packages/98/12/edfdccf3d968ffbb94ac8e48b3172395b6902eb4265bded0b0d07a1652f3/gtextfsm-0.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-403qlws9/gtextfsm/setup.py", line 19, in <module>
        import textfsm
      File "/tmp/pip-install-403qlws9/gtextfsm/textfsm/__init__.py", line 2, in <module>
        __version__ = textfsm.__version__
    **_NameError: name 'textfsm' is not defined_**

Thanks for help this is extremely annoying.
Regards

**Comment by harro** [comment]
I believe pycsco should be using textfsm rather than gtextfsm and I have opened issue [#43 ](https://github.com/jedelman8/pycsco/issues/43) with the maintainer regarding this issue.
