### ISSUE TITLE
TextFSM and german "umlaute" re.unicode option

### ISSUE THREAD

**Issue by hendriklenz** [google/textfsm#49]
Hello,

I use TextFSM and want to use German umlauts like ä,ö and ü in the regular expressions. When I test the regular expression in an editor this works. If I use the expression in a TextFSM template, the values with umlauts are not read. Can TextFSM handle such characters (öäü)?  If so, how?

I use that expression:

Value Required posten ([\w üöä\.-]{28})

Many thanks and greetings
Hendrik

**Comment by hendriklenz** [comment]
I think it's because the regex module is used without the option re.unicode. 
Could that be the cause?

If so, is it possible to use the re.unicode function with TextFSM?

**Comment by hendriklenz** [comment]
The problem is solved. I have used Python version 2.7. After an upgrade to version 3.7 it works now.

**Comment by harro** [comment]
The current python-v3 pull request should address the issue for python2.7 as well.
