### ISSUE TITLE
Wiki Documentation Error

### ISSUE THREAD

**Issue by matthewjchou** [google/textfsm#51]
Under State Definitions in TextFSM on the wiki, it states that a white space followed by a carat is necessary for rules, but I believe it's actually 2 spaces. 1 space gave me the error of "missing white space or carat before rule". Should clarify that it's 2.

**Comment by harro** [comment]
Interesting. I think that might actually be a bug (i.e. typo)?
But the convention of two spaces is so well established it's probably better to update the documentation as you suggest.

**Comment by harro** [comment]
Fixed with pull #56 it can now be 1 or 2 spaces.
