### ISSUE TITLE
How to match string from end

### ISSUE THREAD

**Issue by ajayreddy28390** [google/textfsm#53]
How to match a string from end:

**String:**
Github is good

Want to match good from right to left

```
Value string ((\S+)$)

Start
    ${string} -> Record
```

**Expected Answer:**
good

**Result:** 
[ ]

**Comment by buxtronix** [comment]
This does it, it uses non-greedy matching:

```
Value string (\S+)

Start
    ^.*?${string}$$ -> Record
```
