### ISSUE TITLE
How to record instances of a variable which can occur upto 512 times

### ISSUE THREAD

**Issue by smitharajan** [google/textfsm#54]
I am using textfsm to modify few old configurations to newly supported format.
So for that i need the client id's and its interface specifications from below configs
So here is my old configs.

cluster xyz
          client c1
               interface port-channel 40
         client c2
               interface port-channel 42
         client c3
               interface port-channel 55
         client c4
               interface port-channel 66

This  **may** go upto 512 clients under cluster

The Table should be like this
---------------------------------------------------------------------------------------------------
xyz |  c1   |  port-channel 40
      |   c2  |  port-channel 42
      |   c3  |  port-channel 55
...
...

  Can somebody please help me on this ?

**Comment by buxtronix** [comment]
Would this work?

```
Value Filldown Cluster (\S+)
Value Client (\S+)
Value Required Interface (\S.*)

Start
  ^cluster ${Cluster}
  ^client ${Client}
  ^interface ${Interface} -> Record
```

Your input data gives the following output:

```
["Cluster","Client","Interface"]
["xyz","c1","port-channel 40"]
["xyz","c2","port-channel 42"]
["xyz","c3","port-channel 55"]
["xyz","c4","port-channel 66"]
```

**Comment by smitharajan** [comment]
Thanks for the reply.

I ran the template you shared for the input , attached raw_input.txt. But it does not record the client at all
[raw_inp.txt](https://github.com/google/textfsm/files/3358767/raw_inp.txt)

Suppose one of the client wont have interface configuration in it , then it wont record rite

**Comment by buxtronix** [comment]
The new input you've provided has a different format to the original one. So it depends if you're parsing the first, the second, or both may be present at the same time.

**Comment by harro** [comment]
@smitharajan did the suggested approach by @buxtronix address your issue?
