### ISSUE TITLE
Parentheses in variable definition 

### ISSUE THREAD

**Issue by nagy3n** [google/textfsm#67]
I had an issue where i put an opening parenthesis in my variable definition as such:
`Value interface ([^ (]+)`

Textfsm instance raised a TextFSMTemplateError exception 
`Value '([^ (]+)' must be contained within a '()' pair.`

Is this a bug?

**Comment by harro** [comment]
Yes, looks like a bug.
Fix is in [value_parse](https://github.com/google/textfsm/tree/value_parse)

**Comment by harro** [comment]
#68
