### ISSUE TITLE
Publish textfsm to PyPI

### ISSUE THREAD

**Issue by colinmcintosh** [google/textfsm#7]
There is currently two packages on PyPI for textfsm:

https://pypi.python.org/pypi/textfsm looks like it is out of date and may or may not be official.

https://pypi.python.org/pypi/gtextfsm looks like is more up-to-date but is not official. 

Can someone from Google please publish an official package on PyPI that is up-to-date?

**Comment by harro** [comment]
0.3.2 is up on the site
