### ISSUE TITLE
Parse Text on multiple lines

### ISSUE THREAD

**Issue by aanghel123** [google/textfsm#73]
Hi,

I am trying to parse the following text:
##############################################
++++++++++2020-01-13 11:30:24.875127++++++++++

Connected to branch1-cs02
branch1-cs02# ter len 0
branch1-cs02# ! Tracing to: hub-cs01
branch1-cs02# traceroute 10.128.223.55
Type escape sequence to abort.
Tracing the route to hub-cs01.corp.company.com (10.128.223.55)
VRF info: (vrf in name/id, vrf out name/id)
  1 branch1-vw01-to-branch1-cs02.net.company.com (10.132.65.248) 0 msec 4 msec 0 msec
  2 hub-sw01-vni01.corp.company.com (10.128.220.76) 64 msec 64 msec
    hub-sw01-vni02.corp.company.com (10.128.220.78) 60 msec
  3 hub-cs01-eth1-4.corp.company.com (10.128.220.77) 64 msec
    hub-cs02-eth1-4.corp.company.com (10.128.220.79) 60 msec 56 msec
  4 hub-infw-gi1-2.corp.company.com (10.128.220.50) 60 msec 56 msec 60 msec
  5  *
    hub-cs01.corp.company.com (10.128.223.55) 64 msec 60 msec
branch1-cs02# ! End
branch1-cs02# ! Tracing to: hub-cs02
branch1-cs02# traceroute 10.128.223.56
Type escape sequence to abort.
Tracing the route to hub-cs02.net.company.com (10.128.223.56)
VRF info: (vrf in name/id, vrf out name/id)
  1 branch1-vw01-to-branch1-cs02.net.company.com (10.132.65.248) 0 msec 0 msec 4 msec
  2 hub-sw01-vni02.corp.company.com (10.128.220.78) 60 msec 60 msec
    hub-sw01-vni01.corp.company.com (10.128.220.76) 64 msec
  3 hub-cs02-eth1-4.corp.company.com (10.128.220.79) 64 msec
    hub-cs01-eth1-4.corp.company.com (10.128.220.77) 60 msec 64 msec
  4 hub-infw-gi1-1.corp.company.com (10.128.220.46) 60 msec 56 msec 60 msec
  5 hub-cs02.net.company.com (10.128.223.56) 64 msec 56 msec 64 msec
branch1-cs02# exit

++++++++++2020-01-13 11:31:04.824166++++++++++
##############################################

##############################################
++++++++++2020-01-13 11:30:24.876500++++++++++

Connected to branch1-cs01
branch1-cs01# ter len 0
branch1-cs01# ! Tracing to: hub-cs01
branch1-cs01# traceroute 10.128.223.55
Type escape sequence to abort.
Tracing the route to hub-cs01.corp.company.com (10.128.223.55)
VRF info: (vrf in name/id, vrf out name/id)
  1 branch1-vw01-to-branch1-cs01.net.company.com (10.132.65.246) 0 msec 4 msec 0 msec
  2 hub-sw01-vni01.corp.company.com (10.128.220.76) 68 msec
    hub-sw01-vni02.corp.company.com (10.128.220.78) 60 msec 60 msec
  3 hub-cs01-eth1-4.corp.company.com (10.128.220.77) 60 msec
    hub-cs02-eth1-4.corp.company.com (10.128.220.79) 68 msec
    hub-cs01-eth1-4.corp.company.com (10.128.220.77) 64 msec
  4 hub-infw-gi1-2.corp.company.com (10.128.220.50) 64 msec
    hub-infw-gi1-1.corp.company.com (10.128.220.46) 60 msec 56 msec
  5  *
    hub-cs01.corp.company.com (10.128.223.55) 60 msec 64 msec
branch1-cs02# ! End
branch1-cs01# ! Tracing to: hub-cs02
branch1-cs01# traceroute 10.128.223.56
Type escape sequence to abort.
Tracing the route to hub-cs02.corp.company.com (10.128.223.56)
VRF info: (vrf in name/id, vrf out name/id)
  1 branch1-vw01-to-branch1-cs01.net.company.com (10.132.65.246) 0 msec 0 msec 0 msec
  2 hub-sw01-vni02.corp.company.com (10.128.220.78) 68 msec
    hub-sw01-vni01.corp.company.com (10.128.220.76) 60 msec 60 msec
  3 hub-cs02-eth1-4.corp.company.com (10.128.220.79) 68 msec
    hub-cs01-eth1-4.corp.company.com (10.128.220.77) 64 msec
    hub-cs02-eth1-4.corp.company.com (10.128.220.79) 60 msec
  4 hub-infw-gi1-2.corp.company.com (10.128.220.50) 64 msec 60 msec
    hub-infw-gi1-1.corp.company.com (10.128.220.46) 64 msec
  5 hub-cs02.corp.company.com (10.128.223.56) 64 msec 56 msec 64 msec
branch1-cs01# exit

++++++++++2020-01-13 11:31:04.811355++++++++++
##############################################

FSM file is the following:
Value DEVICE (\S+)
Value TARGET_DEVICE (\S+)
Value TARGET_IP (\d+?\.\d+?\.\d+?\.\d+)
Value List HOP (.*)

Start
  ^${DEVICE}#\s+!\s+Tracing\sto:\s${TARGET_DEVICE} -> Hop

Hop
  ^\S+#\s+traceroute\s+${TARGET_IP}
  ^VRF.*
  ^\s${HOP} -> Continue
  ^\S+#\s+!\s+End -> Record

Here is the result i get:

[{'DEVICE': 'branch1-cs02',
  'HOP': [' 1 branch1-vw01-to-branch1-cs02.net.company.com (10.132.65.248) 0 '
          'msec 4 msec 0 msec',
          ' 2 hub-sw01-vni01.corp.company.com (10.128.220.76) 64 msec 64 msec',
          '   hub-sw01-vni02.corp.company.com (10.128.220.78) 60 msec',
          ' 3 hub-cs01-eth1-4.corp.company.com (10.128.220.77) 64 msec',
          '   hub-cs02-eth1-4.corp.company.com (10.128.220.79) 60 msec 56 msec',
          ' 4 hub-infw-gi1-2.corp.company.com (10.128.220.50) 60 msec 56 msec '
          '60 msec',
          ' 5  *',
          '   hub-cs01.corp.company.com (10.128.223.55) 64 msec 60 msec'],
  'TARGET_DEVICE': 'hub-cs01',
  'TARGET_IP': '10.128.223.55'},
 {'DEVICE': '',
  'HOP': [' 1 branch1-vw01-to-branch1-cs02.net.company.com (10.132.65.248) 0 '
          'msec 0 msec 4 msec',
          ' 2 hub-sw01-vni02.corp.company.com (10.128.220.78) 60 msec 60 msec',
          '   hub-sw01-vni01.corp.company.com (10.128.220.76) 64 msec',
          ' 3 hub-cs02-eth1-4.corp.company.com (10.128.220.79) 64 msec',
          '   hub-cs01-eth1-4.corp.company.com (10.128.220.77) 60 msec 64 msec',
          ' 4 hub-infw-gi1-1.corp.company.com (10.128.220.46) 60 msec 56 msec '
          '60 msec',
          ' 5 hub-cs02.net.company.com (10.128.223.56) 64 msec 56 msec 64 msec',
          ' 1 branch1-vw01-to-branch1-cs01.net.company.com (10.132.65.246) 0 '
          'msec 4 msec 0 msec',
          ' 2 hub-sw01-vni01.corp.company.com (10.128.220.76) 68 msec',
          '   hub-sw01-vni02.corp.company.com (10.128.220.78) 60 msec 60 msec',
          ' 3 hub-cs01-eth1-4.corp.company.com (10.128.220.77) 60 msec',
          '   hub-cs02-eth1-4.corp.company.com (10.128.220.79) 68 msec',
          '   hub-cs01-eth1-4.corp.company.com (10.128.220.77) 64 msec',
          ' 4 hub-infw-gi1-2.corp.company.com (10.128.220.50) 64 msec',
          '   hub-infw-gi1-1.corp.company.com (10.128.220.46) 60 msec 56 msec',
          ' 5  *',
          '   hub-cs01.corp.company.com (10.128.223.55) 60 msec 64 msec'],
  'TARGET_DEVICE': '',
  'TARGET_IP': '10.128.223.55'},
 {'DEVICE': '',
  'HOP': [' 1 branch1-vw01-to-branch1-cs01.net.company.com (10.132.65.246) 0 '
          'msec 0 msec 0 msec',
          ' 2 hub-sw01-vni02.corp.company.com (10.128.220.78) 68 msec',
          '   hub-sw01-vni01.corp.company.com (10.128.220.76) 60 msec 60 msec',
          ' 3 hub-cs02-eth1-4.corp.company.com (10.128.220.79) 68 msec',
          '   hub-cs01-eth1-4.corp.company.com (10.128.220.77) 64 msec',
          '   hub-cs02-eth1-4.corp.company.com (10.128.220.79) 60 msec',
          ' 4 hub-infw-gi1-2.corp.company.com (10.128.220.50) 64 msec 60 msec',
          '   hub-infw-gi1-1.corp.company.com (10.128.220.46) 64 msec',
          ' 5 hub-cs02.corp.company.com (10.128.223.56) 64 msec 56 msec 64 '
          'msec'],
  'TARGET_DEVICE': '',
  'TARGET_IP': '10.128.223.56'}]

I  would like to have a list of dictionaries in the format:
Device:
Target_Device:
Target_IP
HOP:List of all the hops from the traceroute output.

**Comment by geekstrident** [comment]
try to change this line

`  ^\S+#\s+!\s+End -> Record`

to this

`  ^\S+#\s+!\s+End -> Record Start`

**Comment by harro** [comment]
Closing on the assumption that the suggested change fixed the issue. Reopen if that is not the case?
