### ISSUE TITLE
texttable.py conflicts with py-texttable

### ISSUE THREAD

**Issue by jhgit** [google/textfsm#77]
https://pypi.org/project/texttable/ also has a texttable.py

**Comment by harro** [comment]
... also here: https://github.com/foutaise/texttable and here https://github.com/bufordtaylor/python-texttable

Not sure what to say ... we were first but that doesn't amount to much and it is not surprising that other projects have used the same library name.

**Comment by jhgit** [comment]
I was looking at the old version (0.4.1).  The latest (as of 1.1.0) version of textfsm sticks everything into a package directory (site-packages/textfsm/*).  So no conflict.  I am closing this.  Sorry for posting an issue based on older code.
