### ISSUE TITLE
Add release 1.1.1 to Pypi

### ISSUE THREAD

**Issue by smk4664** [google/textfsm#78]
Could we get release 1.1.1 pushed to Pypi?  https://pypi.org/project/textfsm/

**Comment by vnitinv** [comment]
@harro Can you please take this up as there are many fixes that went after 1.1.0 version.

**Comment by itdependsnetworks** [comment]
@harro @buxtronix bump, any chance on getting a new PyPI version releases? It has been nearly 2 years since that has happened.

**Comment by harro** [comment]
Done
