### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by jgroom33** [google/textfsm#8]
Port this wiki into the github Repo
https://code.google.com/archive/p/textfsm/wikis

As a separate markdown file would be great also.

**Comment by itdependsnetworks** [comment]
Came to raise the same issues, impossible to read the current markdown.

**Comment by itdependsnetworks** [comment]
I was able to update the wiki. This can probably be closed.

**Comment by jgroom33** [comment]
Well done sir. Thank you
