### ISSUE TITLE
Lookbehinds are not supported?

### ISSUE THREAD

**Issue by Yakuza-UA** [google/textfsm#83]
I am trying to build some sophisticated template and here's one of my RE patterns

```
Value TYPE ([a-z\s]+)
Value NEXTHOP ((?:\d{1,3}\.){3}\d{1,3})
Value INTERFACE ([A-Za-z0-9\.\/-]+)

  ^\s+${TYPE}(?<=drop|no route|receive|multicast)$$
  ^\s+${TYPE}(?<=nexthop)\s+${NEXTHOP}\s+${INTERFACE}
  ^\s+recursive\s+via\s+${NEXTHOP}
  ^\s+${TYPE}(?<=receive|attached)\s+(?:for|to)\s+${INTERFACE}
```

This is absolutely valid regexp, I've tested it here: https://regex101.com/
However, when I process the file using this TextFSM template, I get this

```
textfsm.parser.TextFSMTemplateError:
Invalid regular expression: '^\s+(?P<TYPE>[a-z\s]+)(?<=drop|no route|receive|multicast)$'.
```

Does it mean lookbehind logic is not supported?
Basically, I'd like to be able to capture TYPE value if it's drop, no route, receive or multicast in one pattern, but then capture TYPE in a different line if it's nexthop

If this is not supported, I will have to define all these keywords in TYPE's pattern and it won't be as universal as my approach.

Regards

**Comment by Yakuza-UA** [comment]
Ok, it's Python, not TextFSM...

```
re.error: look-behind requires fixed-width pattern
```

I will have to find alternative solution. Thanks

**Comment by gachteme** [comment]
I haven't tested it but #38 should add variable length look-ahead/behind functionality.

**Comment by Yakuza-UA** [comment]
@gachteme Thanks. Is plan to add regex engine instead of re (or in addition to)? If that's the case, then yes, it should resolve this problem as I've tested my patterns using RegEx module. Any particular dates for this fix to be merged into master?

**Comment by ionescucosti** [comment]
@Yakuza-UA I have the solution for a single variable (like (type )?${CLASS_MAP_TYPE} ), I need to do that for a "Value List MATCH (match [a-zA-Z0-9\-\_]+)", could you help me?
