### ISSUE TITLE
Text FSM doesnt process this line properly, even when regex says it will.

### ISSUE THREAD

**Issue by sroodman** [google/textfsm#87]
|    |                               |    |Link State|    |   |Speed/ |MTU |Flow |

^\|\s*\|\s*\|\s*\|\s*\w+\s*\w+\s*\|\s*\|\s*\|\s*\w+\/\s*\|\s*\w+\s*\|\s*\w+\s*\|

If this looks wrong because it looks like something is removing the \ before the |

**Comment by diepes** [comment]
@sroodman put your regex in code block

`^\|(\s*\S*\s*\|)+`

**Comment by harro** [comment]
@sroodman did the fix suggested by @diepes address your issue?

**Comment by geekstrident** [comment]
try to change

`^|\s*|\s*|\s*|\s*\w+\s*\w+\s*|\s*|\s*|\s*\w+/\s*|\s*\w+\s*|\s*\w+\s*|`

to this

`^\|\s*\|\s*\|\s*\|\s*\w+\s*\w+\s*\|\s*\|\s*\|\s*\w+/\s*\|\s*\w+\s*\|\s*\w+\s*\|`

or this

`^[|]\s*[|]\s*[|]\s*[|]\s*\w+\s*\w+\s*[|]\s*[|]\s*[|]\s*\w+/\s*[|]\s*\w+\s*[|]\s*\w+\s*[|]`

**Comment by harro** [comment]
No response, assuming resolved.
