### ISSUE TITLE
juniper_bgp_summary_template assumes record ends on IPv6 RIB

### ISSUE THREAD

**Issue by ytti** [google/textfsm#9]
https://github.com/google/textfsm/blob/master/examples/juniper_bgp_summary_template

seems to assume every neighbour has IPV6 RIB which terminates record. Obviously this is not true, neighbours can have arbitrary set of RIBs and record is terminated when we introduce new neighbour or at double new line.

How can this be expressed in textfsm? Example should reflect this, having neighbor with just inet4, just inet6 and both (There could be many others too, so we can't create exhaustive list).

**Comment by itdependsnetworks** [comment]
Can you provide sample data of what you are seeing?

**Comment by ytti** [comment]
No, I don' have that kind of network right now, but I've had one. But perhaps this will help:
```
...
204.42.110.7          65000          0          0       0       1 9w6d 1:53:20 Active
204.42.110.10         65000          0          0       0       0 21w2d 18:34:56 Active
204.42.110.13         65000      13861      13783       0       7  4d 9:47:15 Establ
  inet.0: 3/28/28/0
  inet.2: 1/2/2/0
204.42.110.15         65000      12955      13780       0      28  4d 9:46:03 Establ
  inet.0: 94/130/130/0
  inet.2: 127/130/130/0
204.42.110.16         65000      12938      13782       0       8  4d 9:47:00 Establ
  inet.0: 21/60/60/0
  inet.2: 23/59/59/0
204.42.110.19         65000     177865     343167       0      13 8w5d 13:10:49 Establ
  inet.0: 201/204/204/0
204.42.110.21         65000          0          0       0       4 11w4d 12:20:39 Active
204.42.110.22         65000          0          0       0      21 4d 13:39:57 Active
...
```


BGP transport and BGP AFI/SAFI are decoupled. Just because you have IPv6 transport there are no implicit AFI/SAFI which are transported over it. IPv6 transport be carrying only IPv4 unicast AFI/SAFI, or it could be carrying 10 different AFI/SAFIs.

**Comment by itdependsnetworks** [comment]
Found this on github, this would be a good example, correct? 
```
root> show bgp summary
Groups: 6 Peers: 12 Down peers: 6
Table          Tot Paths  Act Paths Suppressed    History Damp State    Pending
inet.0
                       9          7          0          0          0          0
inet6.0
                       0          0          0          0          0          0
Peer                     AS      InPkt     OutPkt    OutQ   Flaps Last Up/Dwn State|#Active/Received/Accepted/Damped...
10.101.1.1            65011         25         27       0       8        9:17 2/3/2/0              0/0/0/0
10.101.1.5            65012         23         29       0       8        9:18 1/2/1/0              0/0/0/0
10.101.2.1            65021         22         25       0       8        9:17 1/1/1/0              0/0/0/0
10.101.2.5            65022         22         25       0       9        9:17 1/1/1/0              0/0/0/0
10.101.3.1            65031         22         24       0       9        9:16 1/1/1/0              0/0/0/0
10.101.3.5            65032         22         24       0       8        9:12 1/1/1/0              0/0/0/0
2001:db8::1:1         65011         24         25       0       7        9:12 Establ
  inet6.0: 0/0/0/0
2001:db8::1:5         65012         25         25       0       7        9:13 Establ
  inet6.0: 0/0/0/0
2001:db8::2:1         65021         24         25       0       6        9:14 Establ
  inet6.0: 0/0/0/0
2001:db8::2:5         65022         23         25       0       7        9:17 Establ
  inet6.0: 0/0/0/0
2001:db8::3:1         65031         24         25       0       6        9:14 Establ
  inet6.0: 0/0/0/0
2001:db8::3:5         65032         24         25       0       7        9:19 Establ
  inet6.0: 0/0/0/0```

**Comment by ytti** [comment]
That is example which shows the template works, my point is, inet6.0 cannot be thought as it terminates the list of RIBs and next record will follow

**Comment by LegNBass** [comment]
I have opened a [pull request](https://github.com/google/textfsm/pull/17) that I believe solves this problem.

With that code change, you are able to treat a line as both an indication of the end of the previous record and as the first line in a new record. This allows for an arbitrary number of values to be aggregated into a List, with the start of the next record immediately following.

**Comment by harro** [comment]
I have opened [pull request](https://github.com/google/textfsm/pull/23) to fix the example.
