### ISSUE TITLE
Stuck, can't get passed this error, please help.

### ISSUE THREAD

**Issue by DelmiroCampelo** [google/textfsm#91]
I’m getting the following error when trying to parse some ouput using TextFSM in Ansible. I tried specifying the python interpreter path and it didn’t work. I can’t solve this issue myself for some reason, any help is appreciated.

Error:
“parse_cli_textfsm filter requires TextFSM library to be installed”

[all:vars]
ansible_python_interpreter="/opt/rh/rh-python36/root/usr/bin/python"
[root@server ansible]# ansible –version
wansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules',u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
[root@server ansible]# which python
/opt/rh/rh-python36/root/usr/bin/python

[root@server ansible]# pip3 install textfsm
Requirement already satisfied: textfsm in /root/.local/lib/python3.6/site-packages (1.1.0)
Requirement already satisfied: six in /root/.local/lib/python3.6/site-packages (from textfsm) (1.15.0)
Requirement already satisfied: future in /root/.local/lib/python3.6/site-packages (from textfsm) (0.18.2)
[root@server ansible]#

![Ansible3](https://user-images.githubusercontent.com/80293583/111558496-dda12a80-875c-11eb-9cf7-9d9a9352f937.png)

**Comment by buxtronix** [comment]
This is probably something to do with Ansible. I'd investigate their support forums for this issue.

**Comment by harro** [comment]
Closing as this is a pretty stale issue - please reopen if this is still a concern?
