### ISSUE TITLE
Simple template and text can take minutes to parse???

### ISSUE THREAD

**Issue by allan-silverstein** [google/textfsm#92]
Hello,
I've been using textfsm quite successfully for a while now and it works great.  I've recently run into a problem where a template I put together was taking an extremely long time to complete (minutes...).  I removed most of the template and cli output to make troubleshooting easier.  The problem is with the "comma" after as_path.  Without the comma, it completes instantaneous.  With the comma, it can take minutes depending on the number of lines in the text that it is parsing.  Ultimately I'm trying to extract the AS path from lines where the AS path ends with or without a "comma".

When I put my regex expressions in reg101 tester it works... 

The statement that takes a long time is 

  ^\s+${as_path}, -> Record

textfsm:

```
Value Required as_path (([\d]+\s*)+)

Start
  ^\s+${as_path}, -> Record
# ^\s+${as_path}$$ -> Record
```

Text to parse
```
  4210010000 4210010028, (received & used)
  4210010000 4210010001 4210010000
  4210010000 4210010028, (received & used)
  4210010000 4210010001 4210010000
```

Any ideas what is going wrong here?
Thx
Al

**Comment by buxtronix** [comment]
This is likely due to the regex [backtracking catastrophically](https://www.regular-expressions.info/catastrophic.html).

Making the comma optional appears to avoid this:

``` ^\s+${as_path},? -> Record```

**Comment by allan-silverstein** [comment]
Thank you that seems to be the problem.  I was not even aware of something like this.  Thx again.
