### ISSUE TITLE
Loading "standard template" gives 'str' has no attribute 'seek'

### ISSUE THREAD

**Issue by rtrunk** [google/textfsm#94]
>>> print(textfsm.__version__)
1.1.0
>>> type="nxos"
>>> template = os.environ['NET_TEXTFSM'] + "\cisco_" + type + "_show_cdp_neighbors_detail.textfsm"
>>> print("Using: " + template)
Using: C:\repos\ntc-templates\templates\cisco_nxos_show_cdp_neighbors_detail.textfsm
>>> try:
...     mylist=textfsm.TextFSM(template)
... except Exception as e:
...     print(e)
...
'str' object has no attribute 'seek'
>>>
>>>

**Comment by geekstrident** [comment]
change this line

```
mylist=textfsm.TextFSM(template)
```
to
```
from io import StringIO
mylist = textfsm.TextFSM(StringIO(template))
```
